[project]
name = "msl-equipment-resources"
dynamic = ["version"]
requires-python = ">=3.8"
description = "Resources to communicate with equipment"
license = {file = "LICENSE.txt"}
readme = "README.md"
dependencies = [
    "msl-equipment",
    "numpy",
]
keywords = [
    "MSL",
    "equipment",
    "measurement",
    "acquisition",
    "17025",
]
authors = [
    {name = "Measurement Standards Laboratory of New Zealand", email = "info@measurement.govt.nz"},
]
maintainers = [
    {name = "Joseph Borbely", email = "joseph.borbely@measurement.govt.nz"},
    {name = "Rebecca Hawke", email = "rebecca.hawke@measurement.govt.nz"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.uv.sources]
msl-equipment = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/msl"]

[tool.hatch.build.hooks.vcs]
version-file = "src/msl/equipment_resources/_version.py"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../.."
git_describe_command = ["git", "describe", "--dirty", "--tags", "--long", "--match", "resources-v*"]

[tool.mypy]
cache_dir = ".cache/mypy"
platform = "win32"
strict = true
strict_bytes = true

# with the environment variable MYPYPATH=src defined, namespace_packages=true and
# explicit_package_bases=true, the following error goes away
#   Source file found twice under different module names: "packages.resources.src.msl.equipment_resources" and "msl.equipment_resources"
# https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules
namespace_packages = true
explicit_package_bases = true

allow_redefinition = false
allow_untyped_globals = false
disallow_any_decorated = true
disallow_any_explicit = false  # true
disallow_any_expr = false  # true
disallow_any_unimported = true
ignore_missing_imports = false
implicit_optional = false
local_partial_types = true
scripts_are_modules = true
warn_no_return = true
warn_unreachable = true
