"""Wrapper around the `avaspec.dll` SDK from Avantes."""

# cSpell: ignore Meas Resp Sens
from __future__ import annotations

from .avaspec import (
    AvaSpec,
    AvsIdentityType,
    BroadcastAnswerType,
    ControlSettingsType,
    DarkCorrectionType,
    DetectorType,
    DeviceConfigType,
    DeviceStatus,
    DynamicStorageType,
    EthernetSettingsType,
    HeartbeatRespType,
    InterfaceType,
    IrradianceType,
    MeasConfigType,
    MeasureCallback,
    OemDataType,
    ProcessControlType,
    SensType,
    SmoothingType,
    SpectrumCalibrationType,
    SpectrumCorrectionType,
    StandAloneType,
    TecControlType,
    TempSensorType,
    TimeStampType,
    TriggerType,
    avaspec_callback,
)

__all__: list[str] = [
    "AvaSpec",
    "AvsIdentityType",
    "BroadcastAnswerType",
    "ControlSettingsType",
    "DarkCorrectionType",
    "DetectorType",
    "DeviceConfigType",
    "DeviceStatus",
    "DynamicStorageType",
    "EthernetSettingsType",
    "HeartbeatRespType",
    "InterfaceType",
    "IrradianceType",
    "MeasConfigType",
    "MeasureCallback",
    "OemDataType",
    "ProcessControlType",
    "SensType",
    "SmoothingType",
    "SpectrumCalibrationType",
    "SpectrumCorrectionType",
    "StandAloneType",
    "TecControlType",
    "TempSensorType",
    "TimeStampType",
    "TriggerType",
    "avaspec_callback",
]
