"""PicoStatus.h from version 11.1.0.418.

The header file defines the status codes returned by a Pico device (a PC Oscilloscope or a Data Logger).
"""

# cSpell: ignore picopp picoipp PRBS AUXIO SMPS CYUSB
from __future__ import annotations

from ctypes import c_uint32, c_void_p
from enum import IntEnum

PICO_INFO = c_uint32
PICO_STATUS = c_uint32
PICO_POINTER = c_void_p


class PicoInfo(IntEnum):
    """Unit information identifiers for querying Pico device details.

    Attributes:
        DRIVER_VERSION (int): PicoSDK driver version, `0`.
        USB_VERSION (int): USB version (e.g., USB 2.0 or USB 3.0), `1`.
        HARDWARE_VERSION (int): Hardware version of the PicoScope, `2`.
        VARIANT_INFO (int):  Device model or variant identifier, `3`.
        BATCH_AND_SERIAL (int): Batch and serial number of the device, `4`.
        CAL_DATE (int): Device calibration date, `5`.
        KERNEL_VERSION (int): Kernel driver version, `6`.
        DIGITAL_HARDWARE_VERSION (int): Digital board hardware version, `7`.
        ANALOGUE_HARDWARE_VERSION (int): Analogue board hardware version, `8`.
        FIRMWARE_VERSION_1 (int): First part of the firmware version, `9`.
        FIRMWARE_VERSION_2 (int): Second part of the firmware version, `10`.
        MAC_ADDRESS (int): MAC address of device, `11`.
        SHADOW_CAL (int): Shadow calibration, `12`.
        IPP_VERSION (int): Version of picoipp library, `13`.
        DRIVER_PATH (int): Driver path, `14`.
        FIRMWARE_VERSION_3 (int): Third part of the firmware version, `15`.
        FRONT_PANEL_FIRMWARE_VERSION (int): Front panel firmware version, `16`.
        BOOTLOADER_VERSION (int): Bootloader version, `0x10000001`.
    """

    DRIVER_VERSION = 0x00000000
    USB_VERSION = 0x00000001
    HARDWARE_VERSION = 0x00000002
    VARIANT_INFO = 0x00000003
    BATCH_AND_SERIAL = 0x00000004
    CAL_DATE = 0x00000005
    KERNEL_VERSION = 0x00000006
    DIGITAL_HARDWARE_VERSION = 0x00000007
    ANALOGUE_HARDWARE_VERSION = 0x00000008
    FIRMWARE_VERSION_1 = 0x00000009
    FIRMWARE_VERSION_2 = 0x0000000A
    MAC_ADDRESS = 0x0000000B
    SHADOW_CAL = 0x0000000C
    IPP_VERSION = 0x0000000D
    DRIVER_PATH = 0x0000000E
    FIRMWARE_VERSION_3 = 0x0000000F
    FRONT_PANEL_FIRMWARE_VERSION = 0x00000010
    BOOTLOADER_VERSION = 0x10000001


PICO_OK: int = 0

Error: dict[int, str] = {
    PICO_OK: "PICO_OK: The PicoScope is functioning correctly",
    0x00000001: "PICO_MAX_UNITS_OPENED: An attempt has been made to open more than MAX_UNITS",
    0x00000002: "PICO_MEMORY_FAIL: Not enough memory could be allocated on the host machine",
    0x00000003: "PICO_NOT_FOUND: No Pico Technology device could be found",
    0x00000004: "PICO_FW_FAIL: Unable to download firmware",
    0x00000005: "PICO_OPEN_OPERATION_IN_PROGRESS: The driver is busy opening a device",
    0x00000006: "PICO_OPERATION_FAILED: An unspecified failure occurred",
    0x00000007: "PICO_NOT_RESPONDING: The PicoScope is not responding to commands from the PC",
    0x00000008: "PICO_CONFIG_FAIL: The configuration information in the PicoScope is corrupt or missing",
    0x00000009: "PICO_KERNEL_DRIVER_TOO_OLD: The picopp.sys file is too old to be used with the device driver",
    0x0000000A: "PICO_EEPROM_CORRUPT: The EEPROM has become corrupt, so the device will use a default setting",
    0x0000000B: "PICO_OS_NOT_SUPPORTED: The operating system on the PC is not supported by this driver",
    0x0000000C: "PICO_INVALID_HANDLE: There is no device with the handle value passed",
    0x0000000D: "PICO_INVALID_PARAMETER: A parameter value is not valid",
    0x0000000E: "PICO_INVALID_TIMEBASE: The timebase is not supported or is invalid",
    0x0000000F: "PICO_INVALID_VOLTAGE_RANGE: The voltage range is not supported or is invalid",
    0x00000010: "PICO_INVALID_CHANNEL: The channel number is not valid on this device or no channels have been set",
    0x00000011: "PICO_INVALID_TRIGGER_CHANNEL: The channel set for a trigger is not available on this device",
    0x00000012: "PICO_INVALID_CONDITION_CHANNEL: The channel set for a condition is not available on this device",
    0x00000013: "PICO_NO_SIGNAL_GENERATOR: The device does not have a signal generator",
    0x00000014: "PICO_STREAMING_FAILED: Streaming has failed to start or has stopped without user request",
    0x00000015: "PICO_BLOCK_MODE_FAILED: Block failed to start - a parameter may have been set wrongly",
    0x00000016: "PICO_NULL_PARAMETER: A parameter that was required is NULL",
    0x00000017: "PICO_ETS_MODE_SET: The current functionality is not available while using ETS capture mode",
    0x00000018: "PICO_DATA_NOT_AVAILABLE: No data is available from a run block call",
    0x00000019: "PICO_STRING_BUFFER_TO_SMALL: The buffer passed for the information was too small",
    0x0000001A: "PICO_ETS_NOT_SUPPORTED: ETS is not supported on this device",
    0x0000001B: "PICO_AUTO_TRIGGER_TIME_TO_SHORT: The auto trigger time is less than the time it will take to collect the pre-trigger data",
    0x0000001C: "PICO_BUFFER_STALL: The collection of data has stalled as unread data would be overwritten",
    0x0000001D: "PICO_TOO_MANY_SAMPLES: Number of samples requested is more than available in the current memory segment",
    0x0000001E: "PICO_TOO_MANY_SEGMENTS: Not possible to create number of segments requested",
    0x0000001F: "PICO_PULSE_WIDTH_QUALIFIER: A null pointer has been passed in the trigger function or one of the parameters is out of range",
    0x00000020: "PICO_DELAY: One or more of the hold-off parameters are out of range",
    0x00000021: "PICO_SOURCE_DETAILS: One or more of the source details are incorrect",
    0x00000022: "PICO_CONDITIONS: One or more of the conditions are incorrect",
    0x00000023: "PICO_USER_CALLBACK: The driver's thread is currently in the Ready callback function and therefore the action cannot be carried out",
    0x00000024: "PICO_DEVICE_SAMPLING: An attempt is being made to get stored data while streaming. Either stop streaming by calling stop() or use get_streaming_latest_values()",
    0x00000025: "PICO_NO_SAMPLES_AVAILABLE: Data is unavailable because a run has not been completed",
    0x00000026: "PICO_SEGMENT_OUT_OF_RANGE: The memory segment index is out of range",
    0x00000027: "PICO_BUSY: The device is busy so data cannot be returned yet",
    0x00000028: "PICO_START_INDEX_INVALID: The start time to get stored data is out of range",
    0x00000029: "PICO_INVALID_INFO: The information number requested is not a valid number",
    0x0000002A: "PICO_INFO_UNAVAILABLE: The handle is invalid so no information is available about the device Only PICO_DRIVER_VERSION is available",
    0x0000002B: "PICO_INVALID_SAMPLE_INTERVAL: The sample interval selected for streaming is out of range",
    0x0000002C: "PICO_TRIGGER_ERROR: ETS is set but no trigger has been set. A trigger setting is required for ETS",
    0x0000002D: "PICO_MEMORY: Driver cannot allocate memory",
    0x0000002E: "PICO_SIG_GEN_PARAM: Incorrect parameter passed to the signal generator",
    0x0000002F: "PICO_SHOTS_SWEEPS_WARNING: Conflict between the shots and sweeps parameters sent to the signal generator",
    0x00000030: "PICO_SIG_GEN_TRIGGER_SOURCE: A software trigger has been sent but the trigger source is not a software trigger",
    0x00000031: "PICO_AUX_OUTPUT_CONFLICT: A set_trigger() call has found a conflict between the trigger source and the AUX output enable",
    0x00000032: "PICO_AUX_OUTPUT_ETS_CONFLICT: ETS mode is being used and AUX is set as an input",
    0x00000033: "PICO_WARNING_EXT_THRESHOLD_CONFLICT: Attempt to set different EXT input thresholds set for signal generator and oscilloscope trigger",
    0x00000034: "PICO_WARNING_AUX_OUTPUT_CONFLICT: An set_trigger() function has set AUX as an output and the signal generator is using it as a trigger",
    0x00000035: "PICO_SIG_GEN_OUTPUT_OVER_VOLTAGE: The combined peak-to-peak voltage and the analogue offset voltage exceed the maximum voltage the signal generator can produce",
    0x00000036: "PICO_DELAY_NULL: NULL pointer passed as delay parameter",
    0x00000037: "PICO_INVALID_BUFFER: The buffers for overview data have not been set while streaming",
    0x00000038: "PICO_SIG_GEN_OFFSET_VOLTAGE: The analogue offset voltage is out of range",
    0x00000039: "PICO_SIG_GEN_PK_TO_PK: The analogue peak-to-peak voltage is out of range",
    0x0000003A: "PICO_CANCELLED: A block collection has been cancelled",
    0x0000003B: "PICO_SEGMENT_NOT_USED: The segment index is not currently being used",
    0x0000003C: "PICO_INVALID_CALL: The wrong get_values() function has been called for the collection mode in use",
    0x0000003D: "PICO_GET_VALUES_INTERRUPTED",
    0x0000003F: "PICO_NOT_USED: The function is not available",
    0x00000040: "PICO_INVALID_SAMPLE_RATIO: The aggregation ratio requested is out of range",
    0x00000041: "PICO_INVALID_STATE: Device is in an invalid state",
    0x00000042: "PICO_NOT_ENOUGH_SEGMENTS: The number of segments allocated is fewer than the number of captures requested",
    0x00000043: "PICO_DRIVER_FUNCTION: A driver function has already been called and not yet finished. Only one call to the driver can be made at any one time",
    0x00000044: "PICO_RESERVED: Not used",
    0x00000045: "PICO_INVALID_COUPLING: An invalid coupling type was specified in set_channel()",
    0x00000046: "PICO_BUFFERS_NOT_SET: An attempt was made to get data before a data buffer was defined",
    0x00000047: "PICO_RATIO_MODE_NOT_SUPPORTED: The selected downsampling mode (used for data reduction) is not allowed",
    0x00000048: "PICO_RAPID_NOT_SUPPORT_AGGREGATION: Aggregation was requested in rapid block mode",
    0x00000049: "PICO_INVALID_TRIGGER_PROPERTY: An invalid parameter was passed to set_trigger_channel_properties(), V2",
    0x0000004A: "PICO_INTERFACE_NOT_CONNECTED: The driver was unable to contact the oscilloscope",
    0x0000004B: "PICO_RESISTANCE_AND_PROBE_NOT_ALLOWED: Resistance-measuring mode is not allowed in conjunction with the specified probe",
    0x0000004C: "PICO_POWER_FAILED: The device was unexpectedly powered down",
    0x0000004D: "PICO_SIG_GEN_WAVEFORM_SETUP_FAILED: A problem occurred in set_sig_gen_builtin() or set_sig_gen_arbitrary()",
    0x0000004E: "PICO_FPGA_FAIL: FPGA not successfully set up",
    0x0000004F: "PICO_POWER_MANAGER",
    0x00000050: "PICO_INVALID_ANALOGUE_OFFSET: An impossible analogue offset value was specified in set_channel",
    0x00000051: "PICO_PLL_LOCK_FAILED: There is an error within the device hardware",
    0x00000052: "PICO_ANALOGUE_BOARD: There is an error within the device hardware",
    0x00000053: "PICO_CONFIG_FAIL_AWG: Unable to configure the signal generator",
    0x00000054: "PICO_INITIALISE_FPGA: The FPGA cannot be initialized, so unit cannot be opened",
    0x00000056: "PICO_EXTERNAL_FREQUENCY_INVALID: The frequency for the external clock is not within 15% of the nominal value",
    0x00000057: "PICO_CLOCK_CHANGE_ERROR: The FPGA could not lock the clock signal",
    0x00000058: "PICO_TRIGGER_AND_EXTERNAL_CLOCK_CLASH: You are trying to configure the AUX input as both a trigger and a reference clock",
    0x00000059: "PICO_PWQ_AND_EXTERNAL_CLOCK_CLASH: You are trying to configure the AUX input as both a pulse width qualifier and a reference clock",
    0x0000005A: "PICO_UNABLE_TO_OPEN_SCALING_FILE: The requested scaling file cannot be opened",
    0x0000005B: "PICO_MEMORY_CLOCK_FREQUENCY: The frequency of the memory is reporting incorrectly",
    0x0000005C: "PICO_I2C_NOT_RESPONDING: The I2C that is being actioned is not responding to requests",
    0x0000005D: "PICO_NO_CAPTURES_AVAILABLE: There are no captures available and therefore no data can be returned",
    0x0000005F: "PICO_TOO_MANY_TRIGGER_CHANNELS_IN_USE: The number of trigger channels is greater than 4, except for a PicoScope 4824 where 8 channels are allowed for rising/falling/rising_or_falling trigger directions",
    0x00000060: "PICO_INVALID_TRIGGER_DIRECTION: If you have specified a trigger direction which is not allowed, for example specifying PICO_ABOVE without another condition which crosses a threshold on another channel",
    0x00000061: "PICO_INVALID_TRIGGER_STATES: When more than 4 trigger channels are set and their trigger condition states are not CONDITION_TRUE",
    0x0000005E: "PICO_NOT_USED_IN_THIS_CAPTURE_MODE: The capture mode the device is currently running in does not support the current request",
    0x00000103: "PICO_GET_DATA_ACTIVE",
    0x00000104: "PICO_IP_NETWORKED: Device is IP networked; call is not supported",
    0x00000105: "PICO_INVALID_IP_ADDRESS: An incorrect IP address has been passed to the driver",
    0x00000106: "PICO_IP_SOCKET_FAILED: The IP socket has failed",
    0x00000107: "PICO_IP_SOCKET_TIMED_OUT: The IP socket has timed out",
    0x00000108: "PICO_SETTINGS_FAILED: Failed to apply the requested settings",
    0x00000109: "PICO_NETWORK_FAILED: The network connection has failed",
    0x0000010A: "PICO_WS2_32_DLL_NOT_LOADED: Unable to load the WS2 DLL",
    0x0000010B: "PICO_INVALID_IP_PORT: The specified IP port is invalid",
    0x0000010C: "PICO_COUPLING_NOT_SUPPORTED: The type of coupling requested is not supported on the opened device",
    0x0000010D: "PICO_BANDWIDTH_NOT_SUPPORTED: Bandwidth limiting is not supported on the opened device",
    0x0000010E: "PICO_INVALID_BANDWIDTH: The value requested for the bandwidth limit is out of range",
    0x0000010F: "PICO_AWG_NOT_SUPPORTED: The arbitrary waveform generator is not supported by the opened device",
    0x00000110: "PICO_ETS_NOT_RUNNING: Data has been requested with ETS mode set but run block has not been called, or stop has been called",
    0x00000111: "PICO_SIG_GEN_WHITENOISE_NOT_SUPPORTED: White noise output is not supported on the opened device",
    0x00000112: "PICO_SIG_GEN_WAVE_TYPE_NOT_SUPPORTED: The wave type requested is not supported by the opened device",
    0x00000113: "PICO_INVALID_DIGITAL_PORT: The requested digital port number is out of range (MSOs only)",
    0x00000114: "PICO_INVALID_DIGITAL_CHANNEL: The digital channel is not in the range DIGITAL_CHANNEL0 to DIGITAL_CHANNEL15, the digital channels that are supported",
    0x00000115: "PICO_INVALID_DIGITAL_TRIGGER_DIRECTION: The digital trigger direction is not a valid trigger direction and should be equal in value to one of the DIGITAL_DIRECTION enumerations",
    0x00000116: "PICO_SIG_GEN_PRBS_NOT_SUPPORTED: Signal generator does not generate pseudo-random binary sequence",
    0x00000117: "PICO_ETS_NOT_AVAILABLE_WITH_LOGIC_CHANNELS: When a digital port is enabled, ETS sample mode is not available for use",
    0x00000118: "PICO_WARNING_REPEAT_VALUE: There has been no new sample taken, this value has already been returned previously",
    0x00000119: "PICO_POWER_SUPPLY_CONNECTED: The DC power supply is connected",
    0x0000011A: "PICO_POWER_SUPPLY_NOT_CONNECTED: The DC power supply is not connected",
    0x0000011B: "PICO_POWER_SUPPLY_REQUEST_INVALID: Incorrect power mode passed for current power source",
    0x0000011C: "PICO_POWER_SUPPLY_UNDER_VOLTAGE: The supply voltage from the USB source is too low",
    0x0000011D: "PICO_CAPTURING_DATA: The oscilloscope is in the process of capturing data",
    0x0000011E: "PICO_USB3_0_DEVICE_NON_USB3_0_PORT: A USB 3.0 device is connected to a non-USB 3.0 port",
    0x0000011F: "PICO_NOT_SUPPORTED_BY_THIS_DEVICE: A function has been called that is not supported by the current device",
    0x00000120: "PICO_INVALID_DEVICE_RESOLUTION: The device resolution is invalid (out of range)",
    0x00000121: "PICO_INVALID_NUMBER_CHANNELS_FOR_RESOLUTION: The number of channels that can be enabled is limited in 15 and 16-bit modes",
    0x00000122: "PICO_CHANNEL_DISABLED_DUE_TO_USB_POWERED: USB power not sufficient for all requested channels",
    0x00000123: "PICO_SIG_GEN_DC_VOLTAGE_NOT_CONFIGURABLE: The signal generator does not have a configurable DC offset",
    0x00000124: "PICO_NO_TRIGGER_ENABLED_FOR_TRIGGER_IN_PRE_TRIG: An attempt has been made to define pre-trigger delay without first enabling a trigger",
    0x00000125: "PICO_TRIGGER_WITHIN_PRE_TRIG_NOT_ARMED: An attempt has been made to define pre-trigger delay without first arming a trigger",
    0x00000126: "PICO_TRIGGER_WITHIN_PRE_NOT_ALLOWED_WITH_DELAY: Pre-trigger delay and post-trigger delay cannot be used at the same time",
    0x00000127: "PICO_TRIGGER_INDEX_UNAVAILABLE: The array index points to a non-existent trigger",
    0x00000128: "PICO_AWG_CLOCK_FREQUENCY",
    0x00000129: "PICO_TOO_MANY_CHANNELS_IN_USE: There are more than 4 analogue channels with a trigger condition set",
    0x0000012A: "PICO_NULL_CONDITIONS: The condition parameter is a null pointer",
    0x0000012B: "PICO_DUPLICATE_CONDITION_SOURCE: There is more than one condition pertaining to the same channel",
    0x0000012C: "PICO_INVALID_CONDITION_INFO: The parameter relating to condition information is out of range",
    0x0000012D: "PICO_SETTINGS_READ_FAILED: Reading the meta data has failed",
    0x0000012E: "PICO_SETTINGS_WRITE_FAILED: Writing the meta data has failed",
    0x0000012F: "PICO_ARGUMENT_OUT_OF_RANGE: A parameter has a value out of the expected range",
    0x00000130: "PICO_HARDWARE_VERSION_NOT_SUPPORTED: The driver does not support the hardware variant connected",
    0x00000131: "PICO_DIGITAL_HARDWARE_VERSION_NOT_SUPPORTED: The driver does not support the digital hardware variant connected",
    0x00000132: "PICO_ANALOGUE_HARDWARE_VERSION_NOT_SUPPORTED: The driver does not support the analogue hardware variant connected",
    0x00000133: "PICO_UNABLE_TO_CONVERT_TO_RESISTANCE: Converting a channel's ADC value to resistance has failed",
    0x00000134: "PICO_DUPLICATED_CHANNEL: The channel is listed more than once in the function call",
    0x00000135: "PICO_INVALID_RESISTANCE_CONVERSION: The range cannot have resistance conversion applied",
    0x00000136: "PICO_INVALID_VALUE_IN_MAX_BUFFER: An invalid value is in the max buffer",
    0x00000137: "PICO_INVALID_VALUE_IN_MIN_BUFFER: An invalid value is in the min buffer",
    0x00000138: "PICO_SIG_GEN_FREQUENCY_OUT_OF_RANGE: When calculating the frequency for phase conversion, the frequency is greater than that supported by the current variant",
    0x00000139: "PICO_EEPROM2_CORRUPT: The device's EEPROM is corrupt. Contact Pico Technology support at https://www.picotech.com/tech-support",
    0x0000013A: "PICO_EEPROM2_FAIL: The EEPROM has failed",
    0x0000013B: "PICO_SERIAL_BUFFER_TOO_SMALL: The serial buffer is too small for the required information",
    0x0000013C: "PICO_SIG_GEN_TRIGGER_AND_EXTERNAL_CLOCK_CLASH: The signal generator trigger and the external clock have both been set. This is not allowed",
    0x0000013D: "PICO_WARNING_SIG_GEN_AUXIO_TRIGGER_DISABLED: The AUX trigger was enabled and the external clock has been enabled, so the AUX has been automatically disabled",
    0x0000013E: "PICO_SIG_GEN_GATING_AUXIO_NOT_AVAILABLE: The AUX I/O was set as a scope trigger and is now being set as a signal generator gating trigger. This is not allowed",
    0x0000013F: "PICO_SIG_GEN_GATING_AUXIO_ENABLED: The AUX I/O was set by the signal generator as a gating trigger and is now being set as a scope trigger. This is not allowed",
    0x00000140: "PICO_RESOURCE_ERROR: A resource has failed to initialise",
    0x00000141: "PICO_TEMPERATURE_TYPE_INVALID: The temperature type is out of range",
    0x00000142: "PICO_TEMPERATURE_TYPE_NOT_SUPPORTED: A requested temperature type is not supported on this device",
    0x00000143: "PICO_TIMEOUT: A read/write to the device has timed out",
    0x00000144: "PICO_DEVICE_NOT_FUNCTIONING: The device cannot be connected correctly",
    0x00000145: "PICO_INTERNAL_ERROR: The driver has experienced an unknown error and is unable to recover from this error",
    0x00000146: "PICO_MULTIPLE_DEVICES_FOUND: Used when opening units via IP and more than multiple units have the same IP address",
    0x00000147: "PICO_WARNING_NUMBER_OF_SEGMENTS_REDUCED",
    0x00000148: "PICO_CAL_PINS_STATES: The calibration pin states argument is out of range",
    0x00000149: "PICO_CAL_PINS_FREQUENCY: The calibration pin frequency argument is out of range",
    0x0000014A: "PICO_CAL_PINS_AMPLITUDE: The calibration pin amplitude argument is out of range",
    0x0000014B: "PICO_CAL_PINS_WAVE_TYPE: The calibration pin wave-type argument is out of range",
    0x0000014C: "PICO_CAL_PINS_OFFSET: The calibration pin offset argument is out of range",
    0x0000014D: "PICO_PROBE_FAULT: The probe's identity has a problem",
    0x0000014E: "PICO_PROBE_IDENTITY_UNKNOWN: The probe has not been identified",
    0x0000014F: "PICO_PROBE_POWER_DC_POWER_SUPPLY_REQUIRED: Enabling the probe would cause the device to exceed the allowable current limit",
    0x00000150: "PICO_PROBE_NOT_POWERED_WITH_DC_POWER_SUPPLY: The DC power supply is connected; enabling the probe would cause the device to exceed the allowable current limit",
    0x00000151: "PICO_PROBE_CONFIG_FAILURE: Failed to complete probe configuration",
    0x00000152: "PICO_PROBE_INTERACTION_CALLBACK: Failed to set the callback function, as currently in current callback function",
    0x00000153: "PICO_UNKNOWN_INTELLIGENT_PROBE: The probe has been verified but not known on this driver",
    0x00000154: "PICO_INTELLIGENT_PROBE_CORRUPT: The intelligent probe cannot be verified",
    0x00000155: "PICO_PROBE_COLLECTION_NOT_STARTED: The callback is null, probe collection will only start when first callback is a none null pointer",
    0x00000156: "PICO_PROBE_POWER_CONSUMPTION_EXCEEDED: The current drawn by the probe(s) has exceeded the allowed limit",
    0x00000157: "PICO_WARNING_PROBE_CHANNEL_OUT_OF_SYNC: The channel range limits have changed due to connecting or disconnecting a probe the channel has been enabled",
    0x00000158: "PICO_ENDPOINT_MISSING",
    0x00000159: "PICO_UNKNOWN_ENDPOINT_REQUEST",
    0x0000015A: "PICO_ADC_TYPE_ERROR: The ADC on board the device has not been correctly identified",
    0x0000015B: "PICO_FPGA2_FAILED",
    0x0000015C: "PICO_FPGA2_DEVICE_STATUS",
    0x0000015D: "PICO_ENABLE_PROGRAM_FPGA2_FAILED",
    0x0000015E: "PICO_NO_CHANNELS_OR_PORTS_ENABLED",
    0x0000015F: "PICO_INVALID_RATIO_MODE",
    0x00000160: "PICO_READS_NOT_SUPPORTED_IN_CURRENT_CAPTURE_MODE",
    0x00000161: "PICO_TRIGGER_READ_SELECTION_CHECK_FAILED: These selection tests can be masked together to cover 0x161 to 0x16F",
    0x00000162: "PICO_DATA_READ1_SELECTION_CHECK_FAILED",
    0x00000164: "PICO_DATA_READ2_SELECTION_CHECK_FAILED",
    0x00000168: "PICO_DATA_READ3_SELECTION_CHECK_FAILED",
    0x00000170: "PICO_READ_SELECTION_OUT_OF_RANGE: The requested read is not one of the reads available in enPicoReadSelection",
    0x00000171: "PICO_MULTIPLE_RATIO_MODES: The downsample ratio options cannot be combined together for this request",
    0x00000172: "PICO_NO_SAMPLES_READ: The enPicoReadSelection request has no samples available",
    0x00000173: "PICO_RATIO_MODE_NOT_REQUESTED: The enPicoReadSelection did not include one of the downsample ratios now requested",
    0x00000174: "PICO_NO_USER_READ_REQUESTS_SET: No read requests have been made",
    0x00000175: "PICO_ZERO_SAMPLES_INVALID: The parameter for `number of values` cannot be zero",
    0x00000176: "PICO_ANALOGUE_HARDWARE_MISSING: The analogue hardware cannot be identified; contact Pico Technology Technical Support",
    0x00000177: "PICO_ANALOGUE_HARDWARE_PINS: Setting of the analogue hardware pins failed",
    0x00000178: "PICO_ANALOGUE_HARDWARE_SMPS_FAULT: An SMPS fault has occurred",
    0x00000179: "PICO_DIGITAL_ANALOGUE_HARDWARE_CONFLICT: There appears to be a conflict between the expected and actual hardware in the device; contact Pico Technology Technical Support",
    0x0000017A: "PICO_RATIO_MODE_BUFFER_NOT_SET: One or more of the enPicoRatioMode requested do not have a data buffer set",
    0x0000017B: "PICO_RESOLUTION_NOT_SUPPORTED_BY_VARIANT: The resolution is valid but not supported by the opened device",
    0x0000017C: "PICO_THRESHOLD_OUT_OF_RANGE: The requested trigger threshold is out of range for the current device resolution",
    0x0000017D: "PICO_INVALID_SIMPLE_TRIGGER_DIRECTION: The simple trigger only supports upper edge direction options",
    0x0000017E: "PICO_AUX_NOT_SUPPORTED: The aux trigger is not supported on this variant",
    0x0000017F: "PICO_NULL_DIRECTIONS: The trigger directions pointer may not be null",
    0x00000180: "PICO_NULL_CHANNEL_PROPERTIES: The trigger channel properties pointer may not be null",
    0x00000181: "PICO_TRIGGER_CHANNEL_NOT_ENABLED: A trigger is set on a channel that has not been enabled",
    0x00000182: "PICO_CONDITION_HAS_NO_TRIGGER_PROPERTY: A trigger condition has been set but a trigger property not set",
    0x00000183: "PICO_RATIO_MODE_TRIGGER_MASKING_INVALID: When requesting trigger data, this option can only be combined with the segment header ratio mode flag",
    0x00000184: "PICO_TRIGGER_DATA_REQUIRES_MIN_BUFFER_SIZE_OF_40_SAMPLES: The trigger data buffer must be 40 or more samples in size",
    0x00000185: "PICO_NO_OF_CAPTURES_OUT_OF_RANGE: The number of requested waveforms is greater than the number of memory segments allocated",
    0x00000186: "PICO_RATIO_MODE_SEGMENT_HEADER_DOES_NOT_REQUIRE_BUFFERS: When requesting segment header information, the segment header does not require a data buffer, to get the segment information use get_trigger_info()",
    0x00000187: "PICO_FOR_SEGMENT_HEADER_USE_GET_TRIGGER_INFO: Use get_trigger_info() to retrieve the segment header information",
    0x00000188: "PICO_READ_NOT_SET: A read request has not been set",
    0x00000189: "PICO_ADC_SETTING_MISMATCH: The expected and actual states of the ADCs do not match",
    0x0000018A: "PICO_DATATYPE_INVALID: The requested data type is not one of the enPicoDataType listed",
    0x0000018B: "PICO_RATIO_MODE_DOES_NOT_SUPPORT_DATATYPE: The down sample ratio mode requested does not support the enPicoDataType option chosen",
    0x0000018C: "PICO_CHANNEL_COMBINATION_NOT_VALID_IN_THIS_RESOLUTION: The channel combination is not valid for the resolution",
    0x0000018D: "PICO_USE_8BIT_RESOLUTION",
    0x0000018E: "PICO_AGGREGATE_BUFFERS_SAME_POINTER: The buffer for minimum data values and maximum data values are the same buffers",
    0x0000018F: "PICO_OVERLAPPED_READ_VALUES_OUT_OF_RANGE: The read request number of samples requested for an overlapped operation are more than the total number of samples to capture",
    0x00000190: "PICO_OVERLAPPED_READ_SEGMENTS_OUT_OF_RANGE: The overlapped read request has more segments specified than segments allocated",
    0x00000191: "PICO_CHANNEL_FLAGS_COMBINATIONS_ARRAY_SIZE_TOO_SMALL: The number of channel combinations available are greater than the array size received",
    0x00000192: "PICO_CAPTURES_EXCEEDS_NO_OF_SUPPORTED_SEGMENTS: The number of captures is larger than the maximum number of segments allowed for the device variant",
    0x00000193: "PICO_TIME_UNITS_OUT_OF_RANGE: The time unit requested is not one of the listed enPicoTimeUnits",
    0x00000194: "PICO_NO_SAMPLES_REQUESTED: The number of samples parameter may not be zero",
    0x00000195: "PICO_INVALID_ACTION: The action requested is not listed in enPicoAction",
    0x00000196: "PICO_NO_OF_SAMPLES_NEED_TO_BE_EQUAL_WHEN_ADDING_BUFFERS: When adding buffers for the same read request the buffers for all ratio mode requests have to be the same size",
    0x00000197: "PICO_WAITING_FOR_DATA_BUFFERS: The data is being processed but there is no empty data buffers available, a new data buffer needs to be set sent to the driver so that the data can be processed",
    0x00000198: "PICO_STREAMING_ONLY_SUPPORTS_ONE_READ: When streaming data, only one read option is available",
    0x00000199: "PICO_CLEAR_DATA_BUFFER_INVALID: A clear read request is not one of the enPicoAction listed",
    0x0000019A: "PICO_INVALID_ACTION_FLAGS_COMBINATION: The combination of action flags are not allowed",
    0x0000019B: "PICO_BOTH_MIN_AND_MAX_NULL_BUFFERS_CANNOT_BE_ADDED: PICO_ADD request has been made but both data buffers are set to null and so there is nowhere to put the data",
    0x0000019C: "PICO_CONFLICT_IN_SET_DATA_BUFFERS_CALL_REMOVE_DATA_BUFFER_TO_RESET: A conflict between the data buffers being set has occurred. Please use the PICO_CLEAR_ALL action to reset",
    0x0000019D: "PICO_REMOVING_DATA_BUFFER_ENTRIES_NOT_ALLOWED_WHILE_DATA_PROCESSING: While processing data, buffers cannot be removed from the data buffers list",
    0x00000200: "PICO_CYUSB_REQUEST_FAILED: An USB request has failed",
    0x00000201: "PICO_STREAMING_DATA_REQUIRED: A request has been made to retrieve the latest streaming data, but with either a null pointer or an array size set to zero",
    0x00000202: "PICO_INVALID_NUMBER_OF_SAMPLES: A buffer being set has a length that is invalid (i.e., less than zero)",
    0x00000203: "PICO_INVALID_DISTRIBUTION: The distribution size may not be zero",
    0x00000204: "PICO_BUFFER_LENGTH_GREATER_THAN_INT32_T: The buffer length in bytes is greater than a 4-byte word",
    0x00000209: "PICO_PLL_MUX_OUT_FAILED: The PLL has failed",
    0x0000020A: "PICO_ONE_PULSE_WIDTH_DIRECTION_ALLOWED: Pulse width only supports one direction",
    0x0000020B: "PICO_EXTERNAL_TRIGGER_NOT_SUPPORTED: There is no external trigger available on the device specified by the handle",
    0x0000020C: "PICO_NO_TRIGGER_CONDITIONS_SET: The condition parameter is a null pointer",
    0x0000020D: "PICO_NO_OF_CHANNEL_TRIGGER_PROPERTIES_OUT_OF_RANGE: The number of trigger channel properties it outside the allowed range (is less than zero)",
    0x0000020E: "PICO_PROBE_COMPONENT_ERROR: A probe has been plugged into a channel, but can not be identified correctly",
    0x0000020F: "PICO_INCOMPATIBLE_PROBE: The probe is incompatible with the device channel it is connected to. This could lead to error in the measurements",
    0x00000210: "PICO_INVALID_TRIGGER_CHANNEL_FOR_ETS: The requested channel for ETS triggering is not supported",
    0x00000211: "PICO_NOT_AVAILABLE_WHEN_STREAMING_IS_RUNNING: While the device is streaming the get values method is not available",
    0x00000212: "PICO_INVALID_TRIGGER_WITHIN_PRE_TRIGGER_STATE: The requested state is not one of the enSharedTriggerWithinPreTrigger values",
    0x00000213: "PICO_ZERO_NUMBER_OF_CAPTURES_INVALID: The number of captures have to be greater than zero",
    0x00000214: "PICO_INVALID_LENGTH: The quantifier for a pointer, defining the length in bytes is invalid",
    0x00000300: "PICO_TRIGGER_DELAY_OUT_OF_RANGE: The trigger delay is greater than supported by the hardware",
    0x00000301: "PICO_INVALID_THRESHOLD_DIRECTION: The requested threshold direction is not allowed with the specified channel",
    0x00000302: "PICO_INVALID_THRESHOLD_MODE: The requested threshold mode is not allowed with the specified channel",
    0x00000303: "PICO_TIMEBASE_NOT_SUPPORTED_BY_RESOLUTION: The timebase is not supported or is invalid",
    0x00001000: "PICO_INVALID_VARIANT: The device variant is not supported by this current driver",
    0x00001001: "PICO_MEMORY_MODULE_ERROR: The actual memory module does not match the expected memory module",
    0x00002000: "PICO_PULSE_WIDTH_QUALIFIER_LOWER_UPPER_CONFLICT: A null pointer has been passed in the trigger function or one of the parameters is out of range",
    0x00002001: "PICO_PULSE_WIDTH_QUALIFIER_TYPE: The pulse width qualifier type is not one of the listed options",
    0x00002002: "PICO_PULSE_WIDTH_QUALIFIER_DIRECTION: The pulse width qualifier direction is not one of the listed options",
    0x00002003: "PICO_THRESHOLD_MODE_OUT_OF_RANGE: The threshold range is not one of the listed options",
    0x00002004: "PICO_TRIGGER_AND_PULSE_WIDTH_DIRECTION_IN_CONFLICT: The trigger direction and pulse width option conflict with each other",
    0x00002005: "PICO_THRESHOLD_UPPER_LOWER_MISMATCH: The thresholds upper limits and thresholds lower limits conflict with each other",
    0x00002006: "PICO_PULSE_WIDTH_LOWER_OUT_OF_RANGE: The pulse width lower count is out of range",
    0x00002007: "PICO_PULSE_WIDTH_UPPER_OUT_OF_RANGE: The pulse width upper count is out of range",
    0x00002008: "PICO_FRONT_PANEL_ERROR: The devices front panel has caused an error",
    0x0000200B: "PICO_FRONT_PANEL_MODE: The actual and expected mode of the front panel do not match",
    0x0000200C: "PICO_FRONT_PANEL_FEATURE: A front panel feature is not available or failed to configure",
    0x0000200D: "PICO_NO_PULSE_WIDTH_CONDITIONS_SET: When setting the pulse width conditions either the pointer is null or the number of conditions is set to zero",
    0x0000200E: "PICO_TRIGGER_PORT_NOT_ENABLED: A trigger condition exists for a port, but the port has not been enabled",
    0x0000200F: "PICO_DIGITAL_DIRECTION_NOT_SET: A trigger condition exists for a port, but no digital channel directions have been set",
    0x00002010: "PICO_I2C_DEVICE_INVALID_READ_COMMAND",
    0x00002011: "PICO_I2C_DEVICE_INVALID_RESPONSE",
    0x00002012: "PICO_I2C_DEVICE_INVALID_WRITE_COMMAND",
    0x00002013: "PICO_I2C_DEVICE_ARGUMENT_OUT_OF_RANGE",
    0x00002014: "PICO_I2C_DEVICE_MODE: The actual and expected mode do not match",
    0x00002015: "PICO_I2C_DEVICE_SETUP_FAILED: While trying to configure the device, set up failed",
    0x00002016: "PICO_I2C_DEVICE_FEATURE: A feature is not available or failed to configure",
    0x00002017: "PICO_I2C_DEVICE_VALIDATION_FAILED: The device did not pass the validation checks",
    0x00002018: "PICO_INTERNAL_HEADER_ERROR",
    0x00002019: "PICO_FAILED_TO_WRITE_HARDWARE_FAULT: The device couldn't write the channel settings due to a hardware fault",
    0x00003000: "PICO_MSO_TOO_MANY_EDGE_TRANSITIONS_WHEN_USING_PULSE_WIDTH: The number of MSO's edge transitions being set is not supported by this device (RISING, FALLING, or RISING_OR_FALLING)",
    0x00003001: "PICO_INVALID_PROBE_LED_POSITION: A probe LED position requested is not one of the available probe positions in the ProbeLedPosition enum",
    0x00003002: "PICO_PROBE_LED_POSITION_NOT_SUPPORTED: The LED position is not supported by the selected variant",
    0x00003003: "PICO_DUPLICATE_PROBE_CHANNEL_LED_POSITION: A channel has more than one of the same LED position in the ProbeChannelLedSetting struct",
    0x00003004: "PICO_PROBE_LED_FAILURE: Setting the probes LED has failed",
    0x00003005: "PICO_PROBE_NOT_SUPPORTED_BY_THIS_DEVICE: Probe is not supported by the selected variant",
    0x00003006: "PICO_INVALID_PROBE_NAME: The probe name is not in the list of enPicoConnectProbe enums",
    0x00003007: "PICO_NO_PROBE_COLOUR_SETTINGS: The number of colour settings are zero or a null pointer passed to the function",
    0x00003008: "PICO_NO_PROBE_CONNECTED_ON_REQUESTED_CHANNEL: Channel has no probe connected to it",
    0x00003009: "PICO_PROBE_DOES_NOT_REQUIRE_CALIBRATION: Connected probe does not require calibration",
    0x0000300A: "PICO_PROBE_CALIBRATION_FAILED: Connected probe could not be calibrated - hardware fault is a possible cause",
    0x0000300B: "PICO_PROBE_VERSION_ERROR: A probe has been connected, but the version is not recognised",
    0x0000300C: "PICO_PROBE_DOES_NOT_SUPPORT_FREQUENCY_COUNTER: The channel with the frequency counter enabled has a probe connected that does not support this feature",
    0x00004000: "PICO_AUTO_TRIGGER_TIME_TOO_LONG: The requested trigger time is to long for the selected variant",
    0x00005000: "PICO_MSO_POD_VALIDATION_FAILED: The MSO pod did not pass the validation checks",
    0x00005001: "PICO_NO_MSO_POD_CONNECTED: No MSO pod found on the requested digital port",
    0x00005002: "PICO_DIGITAL_PORT_HYSTERESIS_OUT_OF_RANGE: The digital port enum value is not in the enPicoDigitalPortHysteresis declaration",
    0x00005003: "PICO_MSO_POD_FAILED_UNIT",
    0x00005004: "PICO_ATTENUATION_FAILED: The device's EEPROM is corrupt. Contact Pico Technology support at https://www.picotech.com/tech-support",
    0x00005005: "PICO_DC_50OHM_OVER_VOLTAGE_TRIPPED: A channel set to the 50-Ohm path has tripped due to the input signal",
    0x00005006: "PICO_MSO_OVER_CURRENT_TRIPPED: The MSO pod over current protection activated, unplug and re-plug the MSO pod",
    0x00005010: "PICO_NOT_RESPONDING_OVERHEATED: Status error for when the device has overheated",
    0x00005100: "PICO_USB_VERSION_NOT_SUPPORTED: The USB version of the port is not supported by this variant",
    0x00006000: "PICO_HARDWARE_CAPTURE_TIMEOUT: Waiting for the device to capture timed out",
    0x00006001: "PICO_HARDWARE_READY_TIMEOUT: Waiting for the device be ready for capture timed out",
    0x00006002: "PICO_HARDWARE_CAPTURING_CALL_STOP: The driver is performing a capture requested by run_streaming() or run_block() to interrupt this capture call stop() on the device first",
    0x00007000: "PICO_TOO_FEW_REQUESTED_STREAMING_SAMPLES: The number of samples is less than the minimum number allowed",
    0x00007001: "PICO_STREAMING_REREAD_DATA_NOT_AVAILABLE: A streaming capture has been made but re-reading the data is not allowed",
    0x00007002: "PICO_STREAMING_COMBINATION_OF_RAW_DATA_AND_ONE_AGGREGATION_DATA_TYPE_ALLOWED: Streaming allows Raw plus one aggregation type (MinMax, Decimate, Avg/Sum).",
    0x01000000: "PICO_DEVICE_TIME_STAMP_RESET: The time stamp per waveform segment has been reset",
    0x02000001: "PICO_TRIGGER_TIME_NOT_REQUESTED: When requesting the trigger_time_offset() the trigger time has not been set",
    0x02000002: "PICO_TRIGGER_TIME_BUFFER_NOT_SET: Trigger time buffer not set",
    0x02000004: "PICO_TRIGGER_TIME_FAILED_TO_CALCULATE: The trigger time failed to be calculated",
    0x02000008: "PICO_TRIGGER_WITHIN_A_PRE_TRIGGER_FAILED_TO_CALCULATE: The trigger time failed to be calculated",
    0x02000100: "PICO_TRIGGER_TIME_STAMP_NOT_REQUESTED: The trigger time stamp was not requested",
    0x02200000: "PICO_RATIO_MODE_TRIGGER_DATA_FOR_TIME_CALCULATION_DOES_NOT_REQUIRE_BUFFERS: RATIO_MODE_TRIGGER_DATA_FOR_TIME_CALCULATION cannot have a buffer set",
    0x02200001: "PICO_RATIO_MODE_TRIGGER_DATA_FOR_TIME_CALCULATION_DOES_NOT_HAVE_BUFFERS: It is not possible to set a buffer for RATIO_MODE_TRIGGER_DATA_FOR_TIME_CALCULATION therefore information is not available pertaining to samples",
    0x02200002: "PICO_RATIO_MODE_TRIGGER_DATA_FOR_TIME_CALCULATION_USE_GET_TRIGGER_INFO: To get the trigger time use either get_trigger_info() or get_trigger_time_offset() api calls",
    0x02200003: "PICO_STREAMING_DOES_NOT_SUPPORT_TRIGGER_RATIO_MODES: PICO_RATIO_MODE_TRIGGER and RATIO_MODE_TRIGGER_DATA_FOR_TIME_CALCULATION is not supported in streaming capture",
    0x02200004: "PICO_USE_THE_TRIGGER_READ: Only the PICO_TRIGGER_READ may be used to read PICO_RATIO_MODE_TRIGGER and PICO_RATIO_MODE_TRIGGER_FOR_CALCULATION",
    0x02200005: "PICO_USE_A_DATA_READ: One of the PICO_DATA_READs should be used to read: PICO_RATIO_MODE_RAW, PICO_RATIO_MODE_AGGREGATE, PICO_RATIO_MODE_DECIMATE, PICO_RATIO_MODE_AVERAGE",
    0x02200006: "PICO_TRIGGER_READ_REQUIRES_INT16_T_DATA_TYPE: Trigger data always requires a PICO_INT16_T data type",
    0x02200007: "PICO_RATIO_MODE_REQUIRES_NUMBER_OF_SAMPLES_TO_BE_SET: A ratio mode passed to the API call requires the number of samples to be greater than zero",
    0x03000010: "PICO_SIG_GEN_SETTINGS_MISMATCH: Attempted to set up the signal generator with an inconsistent configuration",
    0x03000011: "PICO_SIG_GEN_SETTINGS_CHANGED_CALL_APPLY: The signal generator has been partially reconfigured and the new settings must be applied before it can be paused or restarted",
    0x03000012: "PICO_SIG_GEN_WAVE_TYPE_NOT_SUPPORTED: The wave type is not listed in enPicoWaveType",
    0x03000013: "PICO_SIG_GEN_TRIGGER_TYPE_NOT_SUPPORTED: The trigger type is not listed in enSigGenTrigType",
    0x03000014: "PICO_SIG_GEN_TRIGGERSOURCE_NOT_SUPPORTED: The trigger source is not listed in enSigGenTrigSource",
    0x03000015: "PICO_SIG_GEN_FILTER_STATE_NOT_SUPPORTED: The filter state is not listed in enPicoSigGenFilterState",
    0x03000020: "PICO_SIG_GEN_NULL_PARAMETER: The arbitrary waveform buffer is a null pointer",
    0x03000021: "PICO_SIG_GEN_EMPTY_BUFFER_SUPPLIED: The arbitrary waveform buffer length is zero",
    0x03000022: "PICO_SIG_GEN_RANGE_NOT_SUPPLIED: The signal generator voltage offset and peak to peak have not been set",
    0x03000023: "PICO_SIG_GEN_BUFFER_NOT_SUPPLIED: The signal generator arbitrary waveform buffer not been set",
    0x03000024: "PICO_SIG_GEN_FREQUENCY_NOT_SUPPLIED: The signal generator frequency have not been set",
    0x03000025: "PICO_SIG_GEN_SWEEP_INFO_NOT_SUPPLIED: The signal generator sweep information has not been set",
    0x03000026: "PICO_SIG_GEN_TRIGGER_INFO_NOT_SUPPLIED: The signal generator trigger information has not been set",
    0x03000027: "PICO_SIG_GEN_CLOCK_FREQ_NOT_SUPPLIED: The signal generator clock frequency have not been set",
    0x03000030: "PICO_SIG_GEN_TOO_MANY_SAMPLES: The signal generator arbitrary waveform buffer length is too long",
    0x03000031: "PICO_SIG_GEN_DUTY_CYCLE_OUT_OF_RANGE: The duty cycle value is out of range",
    0x03000032: "PICO_SIG_GEN_CYCLES_OUT_OF_RANGE: The number of cycles is out of range",
    0x03000033: "PICO_SIG_GEN_PRESCALE_OUT_OF_RANGE: The pre-scaler is out of range",
    0x03000034: "PICO_SIG_GEN_SWEEP_TYPE_INVALID: The sweep type is not listed in enPicoSweepType",
    0x03000035: "PICO_SIG_GEN_SWEEP_WAVE_TYPE_MISMATCH: A mismatch has occurred while checking the sweeps wave type",
    0x03000036: "PICO_SIG_GEN_INVALID_SWEEP_PARAMETERS: The sweeps or shots and trigger type are not valid when combined together",
    0x03000037: "PICO_SIG_GEN_SWEEP_PRESCALE_NOT_SUPPORTED: The sweep and prescaler are not valid when combined together",
    0x03000038: "PICO_AWG_OVER_VOLTAGE_RANGE: The potential applied to the AWG output exceeds the maximum voltage range of the AWG",
    0x03000039: "PICO_NOT_LOCKED_TO_REFERENCE_FREQUENCY: The reference signal cannot be locked to",
    0x03000040: "PICO_PERMISSIONS_ERROR: (Linux only) udev rules are incorrectly configured. The user does not have read/write permissions on the device's file descriptor",
    0x03001000: "PICO_PORTS_WITHOUT_ANALOGUE_CHANNELS_ONLY_ALLOWED_IN_8BIT_RESOLUTION: The digital ports without analogue channels are only allowed in 8-bit resolution",
    0x03003001: "PICO_ANALOGUE_FRONTEND_MISSING",
    0x03003002: "PICO_FRONT_PANEL_MISSING",
    0x03003003: "PICO_ANALOGUE_FRONTEND_AND_FRONT_PANEL_MISSING",
    0x03003800: "PICO_DIGITAL_BOARD_HARDWARE_ERROR: The digital board has reported an error to the driver",
    0x03004000: "PICO_FIRMWARE_UPDATE_REQUIRED_TO_USE_DEVICE_WITH_THIS_DRIVER: Checking if the firmware needs updating, the updateRequired parameter is null",
    0x03004001: "PICO_UPDATE_REQUIRED_NULL",
    0x03004002: "PICO_FIRMWARE_UP_TO_DATE",
    0x03004003: "PICO_FLASH_FAIL",
    0x03004004: "PICO_INTERNAL_ERROR_FIRMWARE_LENGTH_INVALID",
    0x03004005: "PICO_INTERNAL_ERROR_FIRMWARE_NULL",
    0x03004006: "PICO_FIRMWARE_FAILED_TO_BE_CHANGED",
    0x03004007: "PICO_FIRMWARE_FAILED_TO_RELOAD",
    0x03004008: "PICO_FIRMWARE_FAILED_TO_BE_UPDATE",
    0x03004009: "PICO_FIRMWARE_VERSION_OUT_OF_RANGE",
    0x03005000: "PICO_OPTIONAL_BOOTLOADER_UPDATE_AVAILABLE_WITH_THIS_DRIVER",
    0x03005001: "PICO_BOOTLOADER_VERSION_NOT_AVAILABLE",
    0x03008000: "PICO_NO_APPS_AVAILABLE",
    0x03008001: "PICO_UNSUPPORTED_APP",
    0x03002000: "PICO_ADC_POWERED_DOWN: The ADC is powered down when trying to capture data",
    0x10000000: "PICO_WATCHDOG_TIMER: An internal error has occurred and a watchdog timer has been called",
    0x10000001: "PICO_IPP_NOT_FOUND: The picoipp library has not been found",
    0x10000002: "PICO_IPP_NO_FUNCTION: A function in the picoipp library does not exist",
    0x10000003: "PICO_IPP_ERROR: The picoipp library call has failed",
    0x10000004: "PICO_SHADOW_CAL_NOT_AVAILABLE: Shadow calibration is not available on this device",
    0x10000005: "PICO_SHADOW_CAL_DISABLED: Shadow calibration is currently disabled",
    0x10000006: "PICO_SHADOW_CAL_ERROR: Shadow calibration error has occurred",
    0x10000007: "PICO_SHADOW_CAL_CORRUPT: The shadow calibration is corrupt",
    0x10000008: "PICO_DEVICE_MEMORY_OVERFLOW: The memory on board the device has overflowed",
    0x10000010: "PICO_ADC_TEST_FAILURE: The device ADC test failed",
    0x11000000: "PICO_RESERVED_1",
    0x20000000: "PICO_SOURCE_NOT_READY: The PicoSource device is not ready to accept instructions",
    0x20000001: "PICO_SOURCE_INVALID_BAUD_RATE",
    0x20000002: "PICO_SOURCE_NOT_OPENED_FOR_WRITE",
    0x20000003: "PICO_SOURCE_FAILED_TO_WRITE_DEVICE",
    0x20000004: "PICO_SOURCE_EEPROM_FAIL",
    0x20000005: "PICO_SOURCE_EEPROM_NOT_PRESENT",
    0x20000006: "PICO_SOURCE_EEPROM_NOT_PROGRAMMED",
    0x20000007: "PICO_SOURCE_LIST_NOT_READY",
    0x20000008: "PICO_SOURCE_FTD2XX_NOT_FOUND",
    0x20000009: "PICO_SOURCE_FTD2XX_NO_FUNCTION",
}
