"""Manage and interface with equipment in the laboratory."""

from __future__ import annotations

from .__about__ import __version__, version_tuple
from .schema import (
    AcceptanceCriteria,
    Accessories,
    Adjustment,
    Alteration,
    Competency,
    CompletedTask,
    Conditions,
    DigitalFormat,
    DigitalReport,
    Equation,
    Equipment,
    Evaluable,
    File,
    Financial,
    Firmware,
    Maintenance,
    Measurand,
    PlannedTask,
    QualityManual,
    Range,
    ReferenceMaterials,
    Serialised,
    Specifications,
    SpecifiedRequirements,
    Status,
)

__all__: list[str] = [
    "AcceptanceCriteria",
    "Accessories",
    "Adjustment",
    "Alteration",
    "Competency",
    "CompletedTask",
    "Conditions",
    "DigitalFormat",
    "DigitalReport",
    "Equation",
    "Equipment",
    "Evaluable",
    "File",
    "Financial",
    "Firmware",
    "Maintenance",
    "Measurand",
    "PlannedTask",
    "QualityManual",
    "Range",
    "ReferenceMaterials",
    "Serialised",
    "Specifications",
    "SpecifiedRequirements",
    "Status",
    "__version__",
    "version_tuple",
]
