"""Manage and interface with equipment in the laboratory."""

from __future__ import annotations

from .__about__ import __version__, version_tuple
from .config import Config
from .enumerations import ATNState, Backend, DataBits, Parity, RENMode, StopBits
from .interfaces import (
    FTDI,
    GPIB,
    NIDAQ,
    SDK,
    USB,
    USBTMC,
    VXI11,
    HiSLIP,
    MessageBased,
    Modbus,
    MSLConnectionError,
    MSLTimeoutError,
    Prologix,
    PyVISA,
    Serial,
    Socket,
)
from .readings import Readings
from .record_types import ConnectionRecord, EquipmentRecord
from .schema import (
    AcceptanceCriteria,
    Accessories,
    Adjustment,
    Alteration,
    CapitalExpenditure,
    Competency,
    CompletedTask,
    Component,
    Conditions,
    Connection,
    CVDEquation,
    Deserialised,
    DigitalFormat,
    DigitalReport,
    Equation,
    Equipment,
    Evaluable,
    File,
    Financial,
    Firmware,
    Interface,
    IssuingLaboratory,
    Maintenance,
    Measurand,
    PerformanceCheck,
    PlannedTask,
    QualityManual,
    Range,
    ReferenceMaterials,
    Register,
    Report,
    Specifications,
    SpecifiedRequirements,
    Status,
    Table,
)

__all__: list[str] = [
    "FTDI",
    "GPIB",
    "NIDAQ",
    "SDK",
    "USB",
    "USBTMC",
    "VXI11",
    "ATNState",
    "AcceptanceCriteria",
    "Accessories",
    "Adjustment",
    "Alteration",
    "Backend",
    "CVDEquation",
    "CapitalExpenditure",
    "Competency",
    "CompletedTask",
    "Component",
    "Conditions",
    "Config",
    "Connection",
    "ConnectionRecord",
    "DataBits",
    "Deserialised",
    "DigitalFormat",
    "DigitalReport",
    "Equation",
    "Equipment",
    "EquipmentRecord",
    "Evaluable",
    "File",
    "Financial",
    "Firmware",
    "HiSLIP",
    "Interface",
    "IssuingLaboratory",
    "MSLConnectionError",
    "MSLTimeoutError",
    "Maintenance",
    "Measurand",
    "MessageBased",
    "Modbus",
    "Parity",
    "PerformanceCheck",
    "PlannedTask",
    "Prologix",
    "PyVISA",
    "QualityManual",
    "RENMode",
    "Range",
    "Readings",
    "ReferenceMaterials",
    "Register",
    "Report",
    "Serial",
    "Socket",
    "Specifications",
    "SpecifiedRequirements",
    "Status",
    "StopBits",
    "Table",
    "__version__",
    "version_tuple",
]

from . import resources as resources
