"""Manage and interface with equipment in the laboratory."""

from __future__ import annotations

from .__about__ import __version__, version_tuple
from .config import Config
from .connections import Connection
from .constants import Backend
from .interfaces import NIDAQ, SDK, Interface, PyVISA
from .schema import (
    AcceptanceCriteria,
    Accessories,
    Adjustment,
    Alteration,
    CapitalExpenditure,
    Competency,
    CompletedTask,
    Component,
    Conditions,
    CVDEquation,
    Deserialised,
    DigitalFormat,
    DigitalReport,
    Equation,
    Equipment,
    Evaluable,
    File,
    Financial,
    Firmware,
    IssuingLaboratory,
    Maintenance,
    Measurand,
    PerformanceCheck,
    PlannedTask,
    QualityManual,
    Range,
    ReferenceMaterials,
    Register,
    Report,
    Specifications,
    SpecifiedRequirements,
    Status,
    Table,
)

__all__: list[str] = [
    "NIDAQ",
    "SDK",
    "AcceptanceCriteria",
    "Accessories",
    "Adjustment",
    "Alteration",
    "Backend",
    "CVDEquation",
    "CapitalExpenditure",
    "Competency",
    "CompletedTask",
    "Component",
    "Conditions",
    "Config",
    "Connection",
    "Deserialised",
    "DigitalFormat",
    "DigitalReport",
    "Equation",
    "Equipment",
    "Evaluable",
    "File",
    "Financial",
    "Firmware",
    "Interface",
    "IssuingLaboratory",
    "Maintenance",
    "Measurand",
    "PerformanceCheck",
    "PlannedTask",
    "PyVISA",
    "QualityManual",
    "Range",
    "ReferenceMaterials",
    "Register",
    "Report",
    "Specifications",
    "SpecifiedRequirements",
    "Status",
    "Table",
    "__version__",
    "version_tuple",
]
