name: Tests

on: [push, pull_request]

env:
  # enable coloured output
  PY_COLORS: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        os: [windows-latest, ubuntu-latest, macos-latest]
        platform: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade .[tests]
      - name: Run tests
        run: |
          python -m pytest
